[package]
name = "bittorrent"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.59", features = ["derive"] }
reqwest = "0.13.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_bencode = "0.2.4"
serde_json = "1.0.149"
